import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from './componet/NavBar';
import Foter from './componet/Foter';
import LegalLayout from './componet/LegalLayout';
import FAQPage from './componet/FAQPage';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Lawyer Database",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavBar></NavBar>
        <div className="m-2">
           {children}
      <LegalLayout></LegalLayout>
      <FAQPage></FAQPage>
      <Foter></Foter>
        </div>
        
      </body>
    </html>
  );
}
